### ISSUE TITLE
DirectoryNotFoundException in 

### ISSUE THREAD

**Issue by stuartowenhood** [baph-omet/Apex-Launcher#48] opened 2021-08-23 12:42 UTC
# Exception Details
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\David\games\Versions\Audio v1'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.GetFiles(String path)
   at ApexLauncher.DownloadForm.RecursiveCopy(String sourceDirectory, String destinationDirectory, Boolean overwriteFile)
   at ApexLauncher.DownloadForm.PatchDownload(IDownloadable download, String destination)
   at ApexLauncher.DownloadForm.Download()

# Configuration
* Current Launcher Version: 1.7.1.0
* Current Game Version: ALPHA 7.3p
* Install Path: C:\Users\David\games

# Files
* `config.txt`
* C:\Users\David\games:
    * C:\Users\David\games\Versions:
        * C:\Users\David\games\Versions\ALPHA 7
        * C:\Users\David\games\Versions\ALPHA 7
        * `Game.exe`
        * `Game.ini`
        * `Game.rgssad`
        * `gif.dll`
        * `RGSS102E.dll`
        * `RGSS104E.dll`
        * `rubyscreen.dll`
    * C:\Users\David\games\Versions:
        * C:\Users\David\games\Versions\ALPHA 7.3p
        * C:\Users\David\games\Versions\ALPHA 7.3p
        * `Game.exe`
        * `Game.ini`
        * `Game.rgssad`
        * `gif.dll`
        * `RGSS102E.dll`
        * `RGSS104E.dll`
        * `rubyscreen.dll`
    * C:\Users\David\games\Versions:
        * C:\Users\David\games\Versions\ALPHA 9
        * `Game.exe`
        * `Game.ini`
        * `Game.rgssad`
        * `gif.dll`
        * `RGSS102E.dll`
        * `RGSS104E.dll`
        * `rgssdisp.dll`
        * `rubyscreen.dll`
    * C:\Users\David\games\Versions:
        * C:\Users\David\games\Versions\ALPHA 9.3p
        * `Game.exe`
        * `Game.ini`
        * `Game.rgssad`
        * `gif.dll`
        * `RGSS102E.dll`
        * `RGSS104E.dll`
        * `rgssdisp.dll`
        * `rubyscreen.dll`

# Environment
* Locale: en-US
* Operating System: Microsoft Windows NT 6.2.9200.0
* .NET Runtime Version: 4.0.30319.42000

**Comment by baph-omet** [comment] 2021-09-13 12:54
This is a duplicate of #36. If you have new information to share, please do so there.

**Closed by baph-omet** 2021-09-13 12:54 UTC
