### ISSUE TITLE
'Unhandled exception'

### ISSUE THREAD

**Issue by akatsuki-kiba** [baph-omet/Apex-Launcher#52] opened 2022-08-03 15:45 UTC
# Exception Details
System.IO.DirectoryNotFoundException: Impossibile trovare una parte del percorso 'C:\Users\Lenovo\Downloads\Versions\Audio v1'.
   in System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   in System.IO.FileSystemEnumerableIterator`1.CommonInit()
   in System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   in System.IO.Directory.GetFiles(String path)
   in ApexLauncher.DownloadForm.RecursiveCopy(String sourceDirectory, String destinationDirectory, Boolean overwriteFile)
   in ApexLauncher.DownloadForm.PatchDownload(IDownloadable download, String destination)
   in ApexLauncher.DownloadForm.Download()

# Configuration
* Current Launcher Version: 1.7.2.0
* Current Game Version: ALPHA 0
* Install Path: C:\Users\Lenovo\Downloads

# Files
* C:\Users\Lenovo\Downloads:
    * C:\Users\Lenovo\Downloads\Versions:
        * C:\Users\Lenovo\Downloads\Versions\ALPHA 9
        * `Game.exe`
        * `Game.ini`
        * `Game.rgssad`
        * `gif.dll`
        * `RGSS102E.dll`
        * `RGSS104E.dll`
        * `rgssdisp.dll`
        * `rubyscreen.dll`
    * C:\Users\Lenovo\Downloads\Versions:
        * C:\Users\Lenovo\Downloads\Versions\ALPHA 9.3p
        * `Game.exe`
        * `Game.ini`
        * `Game.rgssad`
        * `gif.dll`
        * `RGSS102E.dll`
        * `RGSS104E.dll`
        * `rgssdisp.dll`
        * `rubyscreen.dll`

# Environment
* Locale: en-US
* Operating System: Microsoft Windows NT 6.2.9200.0
* .NET Runtime Version: 4.0.30319.42000

**Comment by baph-omet** [comment] 2022-08-03 15:58
Duplicate of #36. If you have anything new to contribute, please do so there.

**Closed by baph-omet** 2022-08-03 15:58 UTC
